/**
 * Visitor Tracking Service
 * 
 * Automatically creates visitor records in Firestore when tourists
 * check in at destinations. This replaces manual data entry by officers.
 * 
 * Records created here will appear in the web dashboard for analysis.
 */

import { collection, addDoc, serverTimestamp, Timestamp } from 'firebase/firestore';
import { db } from './firebaseApp';
import { ensureAuthenticatedUser } from './authService';

const VISITORS_COLLECTION = 'visitors';

/**
 * Record a tourist's visit to a destination
 * 
 * @param {Object} params - Visit parameters
 * @param {string} params.destinationId - Firestore destination ID
 * @param {string} params.destinationName - Name of the destination
 * @param {string} params.category - Destination category (e.g., "Nature", "Heritage")
 * @param {Date} params.visitDate - Date of visit (defaults to now)
 * @param {Object} params.touristProfile - Tourist profile data
 * @returns {Promise<string>} - Created visitor record ID
 */
export async function recordDestinationVisit({
  destinationId,
  destinationName,
  category = '',
  visitDate = new Date(),
  touristProfile = {},
}) {
  try {
    const user = await ensureAuthenticatedUser();

    // Prepare visitor record matching web dashboard schema
    const visitorRecord = {
      // Tourist identity
      touristId: user.uid,
      touristEmail: user.email || touristProfile.email || '',
      
      // Visit details
      arrivalDate: Timestamp.fromDate(visitDate),
      departureDate: null, // Can be updated later if needed
      visitedDestinations: [destinationName], // Store destination name, not ID
      
      // Tourist demographics (from profile)
      origin: touristProfile.homeCity || touristProfile.nationality || 'Unknown',
      purposeOfVisit: 'Leisure', // Default for mobile app tourists
      ageGroup: calculateAgeGroup(touristProfile.age),
      gender: touristProfile.gender || null,
      nationality: touristProfile.nationality || 'Filipino',
      isInternationalVisitor: isInternational(touristProfile.nationality),
      
      // Accommodation (if available)
      accommodationId: null,
      accommodation: null,
      
      // Event (if available)
      eventAttended: null,
      
      // Metadata
      encodedBy: 'mobile-app-auto', // Special marker for auto-generated records
      source: 'mobile-app',
      autoGenerated: true,
      createdAt: serverTimestamp(),
      
      // Additional context
      destinationName,
      category,
    };

    // Write to Firestore
    const docRef = await addDoc(
      collection(db, VISITORS_COLLECTION),
      visitorRecord
    );

    console.log('✅ Visitor record created:', docRef.id);
    return docRef.id;

  } catch (error) {
    console.error('❌ Failed to create visitor record:', error);
    // Don't throw - visitor tracking failure shouldn't block user flow
    // Officers can still manually enter data if needed
    return null;
  }
}

/**
 * Record visit with itinerary context
 * Includes trip name and scheduled time for better analytics
 */
export async function recordItineraryVisit({
  destinationId,
  destinationName,
  category = '',
  visitDate = new Date(),
  touristProfile = {},
  itineraryId = null,
  tripName = null,
  scheduledTime = null,
}) {
  try {
    const user = await ensureAuthenticatedUser();

    const visitorRecord = {
      // Core tourist identity
      touristId: user.uid,
      touristEmail: user.email || touristProfile.email || '',
      
      // Visit details
      arrivalDate: Timestamp.fromDate(visitDate),
      departureDate: null,
      visitedDestinations: [destinationName], // Store destination name, not ID
      
      // Demographics
      origin: touristProfile.homeCity || touristProfile.nationality || 'Unknown',
      purposeOfVisit: 'Leisure',
      ageGroup: calculateAgeGroup(touristProfile.age),
      gender: touristProfile.gender || null,
      nationality: touristProfile.nationality || 'Filipino',
      isInternationalVisitor: isInternational(touristProfile.nationality),
      
      // Itinerary context (unique to mobile app)
      itineraryId,
      tripName,
      scheduledTime,
      wasPlanned: true, // This was from a planned itinerary
      
      // Metadata
      encodedBy: 'mobile-app-auto',
      source: 'mobile-app-itinerary',
      autoGenerated: true,
      createdAt: serverTimestamp(),
      
      // Additional context
      destinationName,
      category,
    };

    const docRef = await addDoc(
      collection(db, VISITORS_COLLECTION),
      visitorRecord
    );

    console.log('✅ Itinerary visit recorded:', docRef.id, 'for', destinationName);
    return docRef.id;

  } catch (error) {
    console.error('❌ Failed to record itinerary visit:', error);
    return null;
  }
}

/**
 * Batch record multiple destinations from a completed day
 * Useful when tourist marks entire day as completed
 */
export async function recordMultipleVisits({
  destinations = [],
  visitDate = new Date(),
  touristProfile = {},
  itineraryId = null,
  tripName = null,
}) {
  if (!destinations.length) return [];

  const recordPromises = destinations.map((dest) =>
    recordItineraryVisit({
      destinationId: dest.placeId || dest.destinationId || dest.id,
      destinationName: dest.placeName || dest.name || dest.title,
      category: dest.category || '',
      visitDate,
      touristProfile,
      itineraryId,
      tripName,
      scheduledTime: dest.visitTime || dest.time,
    })
  );

  return Promise.allSettled(recordPromises);
}

/**
 * Helper: Calculate age group from age number
 */
function calculateAgeGroup(age) {
  if (!age || age < 0) return null;
  
  if (age < 18) return 'Under 18';
  if (age < 25) return '18-24';
  if (age < 35) return '25-34';
  if (age < 45) return '35-44';
  if (age < 55) return '45-54';
  if (age < 65) return '55-64';
  return '65+';
}

/**
 * Helper: Determine if nationality is international
 */
function isInternational(nationality) {
  if (!nationality) return false;
  
  const domestic = [
    'filipino',
    'philippines',
    'ph',
    'fil',
  ];
  
  return !domestic.some(keyword => 
    nationality.toLowerCase().includes(keyword)
  );
}

/**
 * Helper: Get current date in YYYY-MM-DD format
 */
export function formatVisitDate(date = new Date()) {
  return date.toISOString().split('T')[0];
}
