export const brandColors = {
  blue: '#3498DB',
  yellow: '#F4B400',
  red: '#E74C3C',
  green: '#27AE60',
  ink: '#22313F',
  primary: '#27AE60',
  secondary: '#3498DB',
  accent: '#F4B400',
  danger: '#E74C3C',
  lightBackground: '#FBFCFE',
  lightCard: '#F5F8FA',
  darkBackground: '#101820',
  darkCard: '#172433',
};

export const crowdColors = {
  low: brandColors.green,
  moderate: brandColors.yellow,
  busy: brandColors.red,
  crowded: brandColors.red,
};

export const lightColors = {
  background: brandColors.lightBackground,
  surface: '#FFFFFF',
  surfaceMuted: brandColors.lightCard,
  card: '#FFFFFF',
  text: brandColors.ink,
  textMuted: '#64748B',
  textSoft: '#94A3B8',
  border: '#E2E8F0',
  primary: brandColors.primary,
  primarySoft: '#E8F8EF',
  secondary: brandColors.secondary,
  secondarySoft: '#EAF5FD',
  accent: brandColors.accent,
  accentSoft: '#FFF7DD',
  danger: brandColors.danger,
  dangerSoft: '#FDECEA',
  onPrimary: '#FFFFFF',
  success: brandColors.green,
  tab: '#FFFFFF',
  shadow: brandColors.ink,
  input: '#FFFFFF',
  placeholder: '#E0E3E7',
};

export const darkColors = {
  background: brandColors.darkBackground,
  surface: '#172433',
  surfaceMuted: brandColors.darkCard,
  card: brandColors.darkCard,
  text: '#F8FAFC',
  textMuted: '#CBD5E1',
  textSoft: '#94A3B8',
  border: '#314154',
  primary: brandColors.primary,
  primarySoft: '#123927',
  secondary: brandColors.secondary,
  secondarySoft: '#12324B',
  accent: brandColors.accent,
  accentSoft: '#3A2D08',
  danger: brandColors.danger,
  dangerSoft: '#3B201F',
  onPrimary: '#FFFFFF',
  success: brandColors.green,
  tab: '#142033',
  shadow: '#000000',
  input: '#111C2E',
  placeholder: '#26364E',
};
