const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || path.join(process.env.TEMP, 'byanaga-browser-check/node_modules/playwright'));

async function run() {
  const output = path.resolve('.artifacts/ui');
  await fs.mkdir(output, { recursive: true });
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || path.join(process.env.LOCALAPPDATA, 'ms-playwright/chromium-1223/chrome-win64/chrome.exe') });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.setDefaultTimeout(15000);
  try {
    await page.goto('http://localhost:8081', { waitUntil: 'domcontentloaded', timeout: 90000 });
    await page.getByText('Discover Naga City', { exact: true }).waitFor({ timeout: 90000 });
    const skips = page.getByRole('button', { name: 'Skip', exact: true });
    assert.equal(await skips.count(), 2);
    await skips.first().click();
    await page.getByRole('button', { name: 'Continue as Guest', exact: true }).click();
    await page.getByRole('button', { name: 'Skip', exact: true }).click();
    await page.getByRole('button', { name: 'Menu', exact: true }).waitFor();
    await page.screenshot({ path: path.join(output, 'home-mobile.png') });
    const tab = (name) => page.getByRole('tab', { name, exact: true });
    const button = (name) => page.getByRole('button', { name, exact: true });
    const screenshot = async (name) => {
      await page.screenshot({ path: path.join(output, name + '.png') });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, name + ' has page overflow');
    };
    const home = async () => {
      await button('Back to dashboard').click();
      await button('Menu').waitFor();
    };
    const openBasilica = async () => {
      await tab('Explore').click();
      await button('Open Penafrancia Basilica').click();
    };
    await tab('Profile').click();
    await button('Edit Profile').click();
    await screenshot('edit-profile-mobile');
    await page.getByRole('textbox', { name: 'Full Name', exact: true }).fill('');
    await button('Save Changes').click();
    await page.getByText('Please enter your full name.', { exact: true }).waitFor();
    await page.getByRole('textbox', { name: 'Full Name', exact: true }).fill('Test Traveler');
    await page.getByRole('textbox', { name: 'Phone Number', exact: true }).fill('');
    await button('Select nationality').click();
    await page.getByRole('radio', { name: 'Japanese', exact: true }).click();
    await button('Save Changes').click();
    await page.getByText('Test Traveler', { exact: true }).waitFor();
    console.log('PASS profile validation and save');
    await button('Travel Preferences').click();
    await button('Nature').click();
    await button('Walking').click();
    await button('Save Preferences').click();
    await button('Settings').click();
    await screenshot('settings-mobile');
    await page.getByRole('radio', { name: 'Dark Mode', exact: true }).click();
    await screenshot('settings-dark');
    await page.getByRole('radio', { name: 'Follow System', exact: true }).click();
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.waitForFunction(() => getComputedStyle(document.querySelector('[role="radio"][aria-label="Follow System"]')).color !== '');
    assert.equal(await page.getByRole('radio', { name: 'Follow System', exact: true }).getAttribute('aria-checked'), 'true');
    await page.emulateMedia({ colorScheme: 'light' });
    await page.getByRole('switch', { name: 'Promotions', exact: true }).check();
    await page.getByRole('radio', { name: 'Filipino', exact: true }).click();
    await button('Data Sharing Preferences').click();
    await page.getByRole('switch', { name: 'Share anonymous usage data', exact: true }).check();
    await home();
    await button('Menu').click();
    assert.equal(await page.getByRole('switch', { name: 'Promotions', exact: true }).isChecked(), true);
    assert.equal(await page.getByRole('radio', { name: 'Filipino', exact: true }).isChecked(), true);
    console.log('PASS appearance, privacy, notification and language preferences');
    await home();
    await tab('Trips').click();
    await page.getByText('No saved trips yet', { exact: true }).waitFor();
    await screenshot('empty-trips-mobile');
    await button('Explore Places').click();
    await page.getByRole('textbox', { name: 'Search destinations', exact: true }).fill('unmatched-place');
    await page.getByText('No results found', { exact: true }).waitFor();
    await button('Toggle destination filters').click();
    await screenshot('empty-search-mobile');
    await button('Clear Filters').click();
    await button('Open Penafrancia Basilica').click();
    await button('Photos').click();
    await screenshot('photos-mobile');
    assert.equal(await page.getByRole('img', { name: /photo placeholder/ }).count(), 9);
    await button('Interior').click();
    assert.equal(await page.getByRole('img', { name: 'Interior photo placeholder', exact: true }).count(), 2);
    await home();
    await openBasilica();
    await button('Reviews').click();
    await screenshot('reviews-mobile');
    await button('Helpful review by Maria Santos').click();
    assert.equal(await button('Helpful review by Maria Santos').getAttribute('aria-pressed'), 'true');
    await button('Sort reviews').click();
    await page.getByRole('radio', { name: 'Newest', exact: true }).click();
    await home();
    await openBasilica();
    await button('Nearby').click();
    await screenshot('nearby-places-mobile');
    await button('Save Naga Ecological Park').click();
    await button('Nearby Restaurants').click();
    await screenshot('nearby-restaurants-mobile');
    await button('Save Casa Mia Restaurant').click();
    await home();
    await tab('Profile').click();
    await button('Saved Places').click();
    await button('Open Naga Ecological Park').waitFor();
    await button('Open Casa Mia Restaurant').waitFor();
    console.log('PASS gallery filters, reviews, nearby navigation and shared bookmarks');
    await home();
    await openBasilica();
    await button('Add to Itinerary').click();
    await page.getByRole('textbox', { name: 'Trip Name', exact: true }).fill('Weekend in Naga');
    await button('Save Draft').click();
    await button('Open Weekend in Naga').waitFor();
    await button('Open Weekend in Naga').click();
    assert.equal(await page.getByRole('textbox', { name: 'Trip Name', exact: true }).inputValue(), 'Weekend in Naga');
    await button('Save Trip').click();
    await button('Open Weekend in Naga').waitFor();
    console.log('PASS saved-trip empty state, draft, edit and save');
    await tab('Profile').click();
    await button('Emergency Contacts').click();
    await screenshot('emergency-mobile');
    assert.equal(await page.getByRole('button', { name: /^Call / }).count(), 7);
    await home();
    await button('Events').click();
    await context.setOffline(true);
    await page.getByText('No internet connection', { exact: true }).waitFor();
    await screenshot('offline-mobile');
    await button('Retry').click();
    await page.getByText('Still offline. Please reconnect and try again.', { exact: true }).waitFor();
    await context.setOffline(false);
    await page.getByText('Upcoming Events', { exact: true }).waitFor();
    console.log('PASS offline retry and recovery; emergency dial actions present (not called)');
    await home();
    for (const viewport of [{ width: 320, height: 568 }, { width: 430, height: 932 }, { width: 1440, height: 1000 }]) {
      await page.setViewportSize(viewport);
      await tab('Profile').click();
      await button('Edit Profile').click();
      await screenshot('profile-' + viewport.width);
      await button('Save Changes').scrollIntoViewIfNeeded();
      await screenshot('profile-bottom-' + viewport.width);
      await home();
      await button('Menu').click();
      await screenshot('settings-' + viewport.width);
      await home();
    }
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('byanaga.traveler.v1') || '{}').profile?.name === 'Test Traveler');
    await page.reload();
    await page.getByText('Discover Naga City', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Skip', exact: true }).first().click();
    await button('Continue as Guest').click();
    await button('Skip').click();
    await tab('Profile').click();
    await page.getByText('Test Traveler', { exact: true }).waitFor();
    await button('Settings').click();
    assert.equal(await page.getByRole('switch', { name: 'Promotions', exact: true }).isChecked(), true);
    assert.equal(await page.getByRole('radio', { name: 'Filipino', exact: true }).isChecked(), true);
    console.log('PASS 320px, 430px, desktop layouts and persisted state after reload');
    assert.deepEqual(errors, []);
    console.log('ALL_UI_CHECKS_PASSED');
  } catch (error) {
    await page.screenshot({ path: path.join(output, 'failure.png') });
    console.log((await page.locator('body').innerText()).slice(0, 5000));
    throw error;
  } finally {
    await browser.close();
  }
}
run().catch((error) => { console.error(error); process.exitCode = 1; });
